### ISSUE TITLE
Can't open on latest unity 2019.3.0a4

### ISSUE THREAD

**Issue by rootux** [hengineer/CaptainsMess#11]
After upgrade. I get those errors:

"The type or namespace name 'NetworkSystem' does not exist in the namespace 'UnityEngine.Networking' (are you missing an assembly reference?
"

"
Assets/CaptainsMess/CaptainsMessClient.cs(23,35): error CS0246: The type or namespace name 'NetworkDiscovery' could not be found (are you missing a using directive or an assembly reference?)
"
I guess cause the networking library was updated

**Comment by hengineer** [comment]
Thanks for the report, the library definitely needs to be updated. It hasn't had any love for quite some time. I'm actually in the process of finding a network programmer to help me maintain and upgrade it, so hopefully there will be some changes in the next month or two!

**Comment by cmeil** [comment]
Just a tip: If the assembly references get messed-up/lost after upgrading Unity and you're using Visual Studio, I've found that deleting the Visual Studio-generated files and the .vs folder, then recreating them by double-clicking on one of your scripts from within Unity might fix the issue.

Also, I've seen where, even when using the "#using UnityEngine.Networking;" directive doesn't find classes, explicitly referencing the namespace from within code works, for example, "UnityEngine.Networking.NetworkSystem..."

**Comment by hengineer** [comment]
In this case it's probably due to the [deprecation of UNet](https://support.unity3d.com/hc/en-us/articles/360001252086-UNet-Deprecation-FAQ). I'm going to investigate the new system they have planned but I'm also looking into alternatives like [Mirror](https://github.com/vis2k/Mirror) and [Telepathy](https://github.com/vis2k/Telepathy).

**Comment by cmeil** [comment]
UNet is being deprecated, and its libraries are now marked as [obsolete], but it should still be included and functional with Unity 2019.3.0a4.

**Comment by FloDuno** [comment]
I tried to correct those errors, are you interested in a pull request with the fixes ? (I’m using Unity 2020.1.7f1)

**Comment by hengineer** [comment]
Sure! If it works for you then go ahead. I'm not supporting this library at the moment but it's possible some people will still find it helpful.
