### ISSUE TITLE
No example of placing something on the shared world map?

### ISSUE THREAD

**Issue by RobbieOnGithub** [hengineer/CaptainsMess#13]
I just compiled this demo to two iOS devices. Tracking and connection seems to work, but how do you access the shared worldMap to place objects? I'm surprised this example doesn't show anything done in AR once it's connected. Any advice would be greatly appreciated.

**Comment by hengineer** [comment]
I think there's some confusion. CaptainsMess is just a networking library. There is no concept of a "world map" and no AR component.

**Comment by RobbieOnGithub** [comment]
Got it... I was trying to get this demo working
https://github.com/Unity-Technologies/SharedSpheres

Sorry - I 'issued' the wrong github. Feel free to close.
