### ISSUE TITLE
CaptainsMess does not recover from a temporary connection loss

### ISSUE THREAD

**Issue by Nestorferrando** [hengineer/CaptainsMess#7]
Hi! I found that if wifi connection is lost while CaptainsMess is finding a server or the game already started, the following message appears after disconnecting and trying to connect again.

By some reason host doesn't have broadcast addreses
UnityEngine.Networking.NetworkDiscovery:StartAsServer()
CaptainsMessServer:RestartBroadcastInternal() (at Assets/CaptainsMess/CaptainsMessServer.cs:106)

This can be reproduced easily in the ExampleScene by:
1. Load ExampleScene
2. Press autoconnect
3. Disconnect wifi
4. Press Cancel
5. Reconnect wifi.
6. Press autoconnect

I found a solution here here: http://forum.unity3d.com/threads/broadcast-discovery-already-running-startbroadcast-failed-err-8-startserver-listen-failed.357852/

adding a  NetworkTransport.Init(); at the beginning of CaptainsMessNetworkManager.AutoConnect()
and NetworkTransport.Shutdown(); at the end of CaptainsMessNetworkManager.Cancel() solves the issue.

Cheers Néstor.

**Comment by hengineer** [comment]
I added this fix in version 0.5. Thanks!
